{% set name = "hep-viz" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - hep-viz = hep_viz.cli:app

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - typer
    - fastapi
    - uvicorn
    - pandas
    - numpy
    - pyarrow
    - datasets

test:
  imports:
    - hep_viz
  commands:
    - hep-viz --help

about:
  home: https://github.com/FinnbarWilson/hep-viz
  license: MIT
  license_file: ../LICENSE
  summary: A local visualizer for High Energy Physics (HEP) data
  description: |
    hep-viz is a lightweight, high-performance tool designed to visualize 
    high-dimensional particle tracking and calorimeter data directly from 
    your local machine or Python environment.
  dev_url: https://github.com/FinnbarWilson/hep-viz

extra:
  recipe-maintainers:
    - Finnbar Wilson
